version: "3.9"

services:
  api:
    build: .
    container_name: juezia_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://legaluser:legalpassword@db:5432/jueziadb
    networks:
      - juezia_net

  db:
    image: postgres:15
    container_name: juezia_db
    restart: always
    environment:
      POSTGRES_USER: legaluser
      POSTGRES_PASSWORD: legalpassword
      POSTGRES_DB: jueziadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - juezia_net

volumes:
  postgres_data:

networks:
  juezia_net:
